# Generated by Django 6.1 on 2026-08-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(db_index=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='URLShortener',
        ),
    ]
